---
- name: Installing / configuring additional software
  hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: "TYPE"
      prompt: "On which hardware type do you install? (gen)eric, (think)pad"
      default: "gen"
      private: no

  vars:
    GOTOP_VERSION: 3.0.0
    BIN_DIR: "{{ ansible_user_dir }}/.local/bin"

  tasks:
    - name: Common | Including hardware type task
      include: playbooks/hw-{{ TYPE }}.yml

    - name: Common | Creating directories...
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ BIN_DIR }}"
        - "{{ ansible_user_dir }}/.config/Code - OSS"

    - name: Arch !Manjaro tasks
      block:
        - name: Arch !Manjaro | Installing software from aur
          aur:
            name:
              - pamac-aur
            state: latest
      when: ansible_lsb.description != "Manjaro Linux" and ansible_distribution == 'Archlinux'

    - name: Arch Tasks
      block:
        - name: Arch | Installing software from aur
          aur:
            name:
              - networkmanager-l2tp
              - wps-office
            state: latest

        - name: Arch | Installing software
          pacman:
            name:
              - code
              - remmina
              - shfmt
              - cowsay
              - lsb-release
              - networkmanager-strongswan
              - docker
              - docker-compose
              #- go-pie
            state: installed
            update_cache: yes
          become: yes

        - name: Arch | Removing software step 1
          pacman:
            name:
              - accerciser
              - gnome-books
              - gnome-builder
              - dconf-editor
              - devhelp
              - baobab
              - five-or-more
              - four-in-a-row
              - glade
              - gnome-boxes
              - gnome-characters
              - gnome-chess
              - gnome-clocks
              - gnome-dictionary
              - gnome-font-viewer
              - ghex
              - hitori
              - gnome-klotski
              - gnome-logs
              - gnome-mahjongg
              - gnome-mines
              - gnome-nibbles
              - gnome-robots
              - gnome-sudoku
              - gnome-system-monitor
              - gnome-taquin
              - gnome-tetravex
              - gnome-usage
              - gnome-documents
              - epiphany
              - iagno
              - ipython
              - lightsoff
              - gnome-multi-writer
              - gnome-nettool
              - polari
              - quadrapassel
              - gnome-recipes
              - simple-scan
              - gnome-sound-recorder
              - swell-foop
              - sysprof
              - tali
              - gnome-todo
              - xterm
              - totem
              - gnome-devel-docs
              - gnome-getting-started-docs
              - gnome-user-docs
              - gnome-music
              - gnome-photos
              - rygel
              - gnome-screenshot
              - gnome-weather
            state: absent
            update_cache: yes
          become: yes

        - name: Arch | Removing software step 2
          pacman:
            name:
              - yelp
            state: absent
            update_cache: yes
          become: yes
      when: ansible_distribution == 'Archlinux'

    - name: Common | Creating symlink between VS Code - OSS and VS Code - MS for Settings Sync to work...
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - {
            src: "{{ ansible_user_dir }}/.config/Code - OSS",
            dest: "{{ ansible_user_dir }}/.config/Code",
          }

    - name: Common | Downloading gotop...
      unarchive:
        src: "https://github.com/cjbassi/gotop/releases/download/{{ GOTOP_VERSION }}/gotop_{{ GOTOP_VERSION }}_linux_amd64.tgz"
        dest: "{{ BIN_DIR }}"
        creates: "{{ BIN_DIR }}/gotop"
        remote_src: yes
        mode: 0770

    #    - name: Common | Disabling gdm systemd unit
    #      systemd:
    #        name: "{{ item }}"
    #        enabled: no
    #        daemon_reload: yes
    #      become: yes
    #      with_items:
    #        - gdm

    - name: Common | Enable autologin for gnome-keyring in pam module "login"
      pamd:
        name: login
        type: "{{ item.type }}"
        control: "{{ item.control }}"
        module_path: "{{ item.module_path }}"
        new_type: "{{ item.new_type }}"
        new_control: "{{ item.new_control }}"
        new_module_path: "{{ item.new_module_path }}"
        state: after
      with_items:
        - {
            type: "auth",
            control: "include",
            module_path: "system-local-login",
            new_type: "auth",
            new_control: "optional",
            new_module_path: "pam_gnome_keyring.so",
          }
        - {
            type: "session",
            control: "include",
            module_path: "system-local-login",
            new_type: "session",
            new_control: "optional",
            new_module_path: "pam_gnome_keyring.so auto_start",
          }
      become: yes
      tags: pam
