---
- name: Installing prerequirements
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Arch Tasks
      block:
        - name: Arch | Creating directories...
          file:
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_id }}"
            mode: "0750"
            path: "{{ item }}"
            state: directory
          with_items:
            - "{{ ansible_user_dir }}/.ansible/plugins/modules/aur"

        - name: Arch | Installing ansible module for aur
          git:
            repo: https://github.com/kewlfft/ansible-aur.git
            dest: "{{ ansible_user_dir }}/.ansible/plugins/modules/aur"

        - name: Common | Creating user for aur builds
          user:
            name: aur_builder
          become: true

        - name: Common | Allow user aur_builder to use pacman
          lineinfile:
            path: /etc/sudoers.d/aur_builder
            state: present
            line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
            validate: /usr/sbin/visudo -cf %s
            create: true
            owner: root
            group: root
            mode: 0600
          become: true

        - name: Common | Install yay
          kewlfft.aur.aur:
            name: yay
            state: present
          become: true
          become_user: aur_builder
      when: ansible_distribution == 'Archlinux'
