---
- name: Installing prerequirements
  hosts: "{{ custom_hosts | default('127.0.0.1') }}"
  connection: "{{ custom_connection | default('local') }}"
  strategy: linear

  tasks:
    - name: Arch Tasks
      when: ansible_distribution == 'Archlinux'
      block:
        - name: Arch | Creating directories...
          ansible.builtin.file:
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_id }}"
            mode: "0750"
            path: "{{ item }}"
            state: directory
          with_items:
            - "{{ ansible_user_dir }}/.ansible/plugins/modules/aur"

        - name: Arch | Installing required software
          community.general.pacman:
            name:
              - git
            state: present
          become: true

        - name: Arch | Installing ansible module for aur
          ansible.builtin.git:
            repo: https://github.com/kewlfft/ansible-aur.git
            dest: "{{ ansible_user_dir }}/.ansible/plugins/modules/aur"
            version: v0.10.0

        - name: Common | Creating user for aur builds
          ansible.builtin.user:
            name: aur_builder
          become: true

        - name: Common | Allow user aur_builder to use pacman
          ansible.builtin.lineinfile:
            path: /etc/sudoers.d/aur_builder
            state: present
            line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
            validate: /usr/sbin/visudo -cf %s
            create: true
            owner: root
            group: root
            mode: 0600
          become: true
