---

- name: Arch Tasks
  when: ansible_distribution == 'Archlinux'
  block:
    - name: Arch | Installing generic software
      community.general.pacman:
        name:
          - lm_sensors
        state: latest
        update_cache: true
      become: true

    - name: Arch | Installing required software from aur
      kewlfft.aur.aur:
        name:
          #- tuned
          - auto-cpufreq
        state: latest

- name: Common | Enabling systemd units
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
  become: true
  with_items:
    #- tuned
    - auto-cpufreq
