---
- name: Prepare | First Step
  hosts: all
  gather_facts: false
  strategy: linear
  tasks:
    - name: Prepare | Installing python for Ansible
      ansible.builtin.raw: test -e /usr/bin/python || (yes | pacman -Sy python)
      become: true
      changed_when: false

- name: Prepare | Second step
  hosts: all
  gather_facts: true
  tasks:
    - name: Root Tasks
      block:
        - name: Arch | Installing required software
          community.general.pacman:
            name:
              - bash-completion
              - man-db
              - nano
              - qemu-guest-agent
              - spice-vdagent
              # - virtualbox-guest-utils
              - which
              - xdg-user-dirs
            state: present

        - name: Arch | Allow user vagrant become root with password
          ansible.builtin.lineinfile:
            path: /etc/sudoers.d/vagrant
            state: "{{ item.state }}"
            line: "{{ item.line }}"
            validate: /usr/sbin/visudo -cf %s
            create: true
            owner: root
            group: root
            mode: 0640
          with_items:
            - { line: "vagrant ALL=(ALL) NOPASSWD: ALL", state: "absent"}
            - { line: "vagrant ALL=(ALL:ALL) ALL", state: "present"}
      become: true

    #- name: Common | Starting systemd services
    #  ansible.builtin.systemd:
    #    name: "{{ item }}"
    #    enabled: true
    #    daemon_reload: true
    #    state: started
    #  with_items:
    #    - qemu-guest-agent.service
