---

- name: Arch | Installing software for Lenovo Thinkpad notebooks
  pacman:
    name:
      - acpi_call-dkms
      - lm_sensors
      - tlp
      - tlp-rdw
      - tp_smapi
    state: installed
    update_cache: yes
  become: yes

- name: Arch | Installing software from aur
  aur:
    name:
      - thinkfan
    skip_installed: true
  become: yes
  become_user: aur_builder

- name: Common | Enabling tlp systemd unit
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
  become: yes
  with_items:
    - tlp

- name: Common | Masking systemd-rfkill units
  systemd:
    name: "{{ item }}"
    masked: yes
  become: yes
  with_items:
    - systemd-rfkill.service
    - systemd-rfkill.socket
