---
- name: Arch Tasks
  block:
    - name: Arch | Installing software for Lenovo Thinkpad notebooks
      community.general.pacman:
        name:
          - acpi_call-dkms
          - lm_sensors
          #- tlp
          #- tlp-rdw
        state: latest
        update_cache: true
      become: true

    - name: Arch | Installing software from aur
      kewlfft.aur.aur:
        name:
          - thinkfan
          - auto-cpufreq
          - tp_smapi-dkms
        state: latest
  when: ansible_distribution == 'Archlinux'

- name: Common | Enabling systemd units
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
  become: true
  with_items:
    #- tlp
    - auto-cpufreq

- name: Common | Masking systemd-rfkill units
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: true
  become: true
  with_items:
    - systemd-rfkill.service
    - systemd-rfkill.socket
